<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Assets/FYAsset/Scripts/Shared/Hotfix/HotfixStateDecider.cs" Link="HotfixStateDecider.cs" />
  </ItemGroup>
</Project>
