// <auto-generated>
// Generated by BinarySerializerGenerator. Do not edit manually.
// Hash: 94ed5ca4712563eb643f2681020f2f77
// Source: SmokeModel
// </auto-generated>
using System;
using System.IO;

public static class SmokeModel_BinarySerializer
{
    private const string TargetTypeAqn = "SmokeModel, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null";

    private static Type GetTargetType()
    {
        var t = Type.GetType(TargetTypeAqn);
        if (t == null) throw new InvalidOperationException("Target type not found for generated serializer");
        return t;
    }

    public static void Write(BinaryWriter writer, object obj)
    {
        BinaryReflectionSerializer.WriteObject(writer, GetTargetType(), obj);
    }

    public static object Read(BinaryReader reader)
    {
        return BinaryReflectionSerializer.ReadObject(reader, GetTargetType());
    }

    public static void WriteWithHeader(BinaryWriter writer, object obj)
    {
        BinaryHeader.WriteHeader(writer, 1413829460u, 1, 0);
        Write(writer, obj);
    }

    public static object ReadWithHeader(BinaryReader reader)
    {
        var header = BinaryHeader.ReadHeader(reader);
        if (header.Magic != 1413829460u) throw new InvalidDataException("Magic mismatch");
        if (header.SchemaVersion > 1) throw new InvalidDataException("SchemaVersion too new");
        return Read(reader);
    }
}
