using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;

/// <summary>
/// S2: Binary serializer code generator.
/// 扫描 [BinarySerializable] 类型并生成 {TypeName}_BinarySerializer.cs。
/// </summary>
public static class BinarySerializerGenerator
{
    public const string GeneratedDir = "Assets/AboutXLua/Scripts/Utility/Serialization/Generated";
    public const string HashPrefix = "// Hash:";

    [MenuItem("XLua/Serialization/Generate Binary Serializers", false, 30)]
    public static void GenerateMenu()
    {
        GenerateAll();
        AssetDatabase.Refresh();
        Debug.Log("[BinarySerializerGenerator] 生成完成。\n");
    }

    public static void GenerateAll()
    {
        if (!Directory.Exists(GeneratedDir))
        {
            Directory.CreateDirectory(GeneratedDir);
        }

        var types = GetSerializableTypes();
        for (int i = 0; i < types.Count; i++)
        {
            GenerateForType(types[i]);
        }
    }

    public static bool IsStale(Type type)
    {
        string path = GetGeneratedFilePath(type);
        if (!File.Exists(path))
        {
            return true;
        }

        string[] lines = File.ReadAllLines(path);
        string hashLine = lines.FirstOrDefault(l => l.StartsWith(HashPrefix, StringComparison.Ordinal));
        if (string.IsNullOrEmpty(hashLine))
        {
            return true;
        }

        string currentHash = SerializationHashUtility.ComputeTypeHash(type);
        string fileHash = hashLine.Substring(HashPrefix.Length).Trim();
        return !string.Equals(currentHash, fileHash, StringComparison.OrdinalIgnoreCase);
    }

    public static List<Type> GetStaleTypes()
    {
        var types = GetSerializableTypes();
        var stale = new List<Type>();
        for (int i = 0; i < types.Count; i++)
        {
            if (IsStale(types[i]))
            {
                stale.Add(types[i]);
            }
        }

        return stale;
    }

    private static List<Type> GetSerializableTypes()
    {
        var result = new List<Type>();
        var assemblies = AppDomain.CurrentDomain.GetAssemblies();
        for (int i = 0; i < assemblies.Length; i++)
        {
            Type[] types;
            try
            {
                types = assemblies[i].GetTypes();
            }
            catch (ReflectionTypeLoadException e)
            {
                types = e.Types.Where(t => t != null).ToArray();
            }

            for (int j = 0; j < types.Length; j++)
            {
                var t = types[j];
                if (t.GetCustomAttribute<BinarySerializableAttribute>() != null)
                {
                    result.Add(t);
                }
            }
        }

        return result.OrderBy(t => t.FullName).ToList();
    }

    private static void GenerateForType(Type type)
    {
        string hash = SerializationHashUtility.ComputeTypeHash(type);
        string code = BuildCode(type, hash);
        File.WriteAllText(GetGeneratedFilePath(type), code, Encoding.UTF8);
    }

    private static string BuildCode(Type type, string hash)
    {
        string typeName = type.FullName;
        string serializerName = $"{type.Name}_BinarySerializer";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by BinarySerializerGenerator. Do not edit manually.");
        sb.AppendLine($"{HashPrefix} {hash}");
        sb.AppendLine($"// Source: {typeName}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using System.IO;");
        sb.AppendLine();
        sb.AppendLine($"public static class {serializerName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static void Write(BinaryWriter writer, {typeName} obj)");
        sb.AppendLine("    {");
        sb.AppendLine($"        BinaryReflectionSerializer.WriteObject(writer, typeof({typeName}), obj);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {typeName} Read(BinaryReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return ({typeName})BinaryReflectionSerializer.ReadObject(reader, typeof({typeName}));");
        sb.AppendLine("    }");

        var attr = type.GetCustomAttribute<BinarySerializableAttribute>();
        if (attr != null && attr.Magic != 0)
        {
            sb.AppendLine();
            sb.AppendLine($"    public static void WriteWithHeader(BinaryWriter writer, {typeName} obj)");
            sb.AppendLine("    {");
            sb.AppendLine($"        BinaryHeader.WriteHeader(writer, {attr.Magic}u, {attr.SchemaVersion}, 0);");
            sb.AppendLine("        Write(writer, obj);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine($"    public static {typeName} ReadWithHeader(BinaryReader reader)");
            sb.AppendLine("    {");
            sb.AppendLine("        var header = BinaryHeader.ReadHeader(reader);");
            sb.AppendLine($"        if (header.Magic != {attr.Magic}u) throw new InvalidDataException(\"Magic mismatch\");");
            sb.AppendLine($"        if (header.SchemaVersion > {attr.SchemaVersion}) throw new InvalidDataException(\"SchemaVersion too new\");");
            sb.AppendLine("        return Read(reader);");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetGeneratedFilePath(Type type)
    {
        return Path.Combine(GeneratedDir, $"{type.Name}_BinarySerializer.cs");
    }
}
